# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 500)
        Form.setMinimumSize(QtCore.QSize(600, 500))
        Form.setMaximumSize(QtCore.QSize(600, 500))
        Form.setStyleSheet("background-color: rgb(202, 202, 202);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topLevel = QtWidgets.QFrame(Form)
        self.topLevel.setMaximumSize(QtCore.QSize(16777215, 45))
        self.topLevel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.topLevel.setStyleSheet("")
        self.topLevel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topLevel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topLevel.setObjectName("topLevel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.topLevel)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setSpacing(100)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.topLevel)
        self.frame_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_3.setStyleSheet("background-color: rgb(255, 79, 79);\n"
"border-radius: 10px")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(9, 4, -1, 4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Error = QtWidgets.QLabel(self.frame_3)
        self.Error.setStyleSheet("")
        self.Error.setObjectName("Error")
        self.horizontalLayout_2.addWidget(self.Error)
        self.Close_error = QtWidgets.QPushButton(self.frame_3)
        self.Close_error.setMaximumSize(QtCore.QSize(20, 16777215))
        self.Close_error.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.Close_error.setIconSize(QtCore.QSize(32, 32))
        self.Close_error.setCheckable(True)
        self.Close_error.setObjectName("Close_error")
        self.horizontalLayout_2.addWidget(self.Close_error)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.topLevel)
        self.Janela_Central = QtWidgets.QFrame(Form)
        self.Janela_Central.setStyleSheet("")
        self.Janela_Central.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Janela_Central.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Janela_Central.setObjectName("Janela_Central")
        self.Login_Area = QtWidgets.QFrame(self.Janela_Central)
        self.Login_Area.setGeometry(QtCore.QRect(140, 40, 321, 311))
        self.Login_Area.setStyleSheet("background-color: rgb(93, 93, 93);\n"
"border-radius: 20px")
        self.Login_Area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Login_Area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Login_Area.setObjectName("Login_Area")
        self.image = QtWidgets.QFrame(self.Login_Area)
        self.image.setGeometry(QtCore.QRect(120, 30, 80, 71))
        self.image.setStyleSheet("QFrame{\n"
"image: url(:/close_image/kisspng-scalable-vector-graphics-avatar-learning-icon-customer-login-avatar-5a77d3352ad604.7165486515178022931755-removebg-preview.png);\n"
"background-color: rgb(255, 255, 255);\n"
"border:6px solid rgb(53, 53, 53);\n"
"border-radius: 20px\n"
"}")
        self.image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.image.setObjectName("image")
        self.getUser = QtWidgets.QLineEdit(self.Login_Area)
        self.getUser.setGeometry(QtCore.QRect(90, 140, 141, 20))
        self.getUser.setStyleSheet("background-color: rgb(63, 63, 63);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;border:2px solid rgb(255, 255, 127);")
        self.getUser.setMaxLength(12)
        self.getUser.setAlignment(QtCore.Qt.AlignCenter)
        self.getUser.setObjectName("getUser")
        self.getPassword = QtWidgets.QLineEdit(self.Login_Area)
        self.getPassword.setGeometry(QtCore.QRect(90, 190, 141, 20))
        self.getPassword.setStyleSheet("background-color: rgb(63, 63, 63);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(255, 255, 127);")
        self.getPassword.setMaxLength(12)
        self.getPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.getPassword.setAlignment(QtCore.Qt.AlignCenter)
        self.getPassword.setObjectName("getPassword")
        self.Login = QtWidgets.QPushButton(self.Login_Area)
        self.Login.setGeometry(QtCore.QRect(100, 270, 121, 23))
        self.Login.setStyleSheet("QPushButton:pressed{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(63, 63, 63);\n"
"border-radius:10px;\n"
"border:2px solid rgb(255, 255, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.Login.setCheckable(True)
        self.Login.setChecked(False)
        self.Login.setObjectName("Login")
        self.pushButton = QtWidgets.QPushButton(self.Login_Area)
        self.pushButton.setGeometry(QtCore.QRect(20, 230, 75, 23))
        self.pushButton.setStyleSheet("QPushButton:pressed{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(63, 63, 63);\n"
"border-radius:10px;\n"
"border:2px solid rgb(255, 255, 127);\n"
"color:rgb(255, 255, 255)\n"
"}\n"
"    \n"
"")
        self.pushButton.setObjectName("pushButton")
        self.Rodape = QtWidgets.QFrame(self.Janela_Central)
        self.Rodape.setGeometry(QtCore.QRect(0, 419, 601, 61))
        self.Rodape.setStyleSheet("background-color: rgb(66, 66, 66);")
        self.Rodape.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Rodape.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Rodape.setObjectName("Rodape")
        self.Creditos = QtWidgets.QLabel(self.Rodape)
        self.Creditos.setGeometry(QtCore.QRect(490, 10, 91, 20))
        self.Creditos.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Creditos.setObjectName("Creditos")
        self.verticalLayout.addWidget(self.Janela_Central)

        self.retranslateUi(Form)
        self.frame_3.hide()
        QtCore.QMetaObject.connectSlotsByName(Form)







    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Login"))
        self.Error.setText(_translate("Form", "<html><head/><body><p align=\"center\">ERROR</p></body></html>"))
        self.Close_error.setText(_translate("Form", "X"))
        self.getUser.setPlaceholderText(_translate("Form", "USER"))
        self.getPassword.setPlaceholderText(_translate("Form", "PASSWORD"))
        self.Login.setText(_translate("Form", "Logar"))
        self.pushButton.setText(_translate("Form", "REGISTRAR"))
        self.Creditos.setText(_translate("Form", "<html><head/><body><p align=\"center\">Criado por Kaio</p></body></html>"))
import images


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
