# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registro.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        MainWindow.setMaximumSize(QtCore.QSize(500, 500))
        MainWindow.setStyleSheet("background-color: rgb(152, 152, 152);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Janela_Central = QtWidgets.QFrame(self.centralwidget)
        self.Janela_Central.setGeometry(QtCore.QRect(-90, 50, 600, 455))
        self.Janela_Central.setStyleSheet("background-color: rgb(132, 132, 132);")
        self.Janela_Central.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Janela_Central.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Janela_Central.setObjectName("Janela_Central")
        self.Login_Area = QtWidgets.QFrame(self.Janela_Central)
        self.Login_Area.setGeometry(QtCore.QRect(180, 30, 321, 311))
        self.Login_Area.setStyleSheet("background-color: rgb(93, 93, 93);\n"
"border-radius: 20px")
        self.Login_Area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Login_Area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Login_Area.setObjectName("Login_Area")
        self.image = QtWidgets.QFrame(self.Login_Area)
        self.image.setGeometry(QtCore.QRect(120, 30, 80, 71))
        self.image.setStyleSheet("QFrame{\n"
"    background-image: url(:/close_image/kisspng-scalable-vector-graphics-avatar-learning-icon-customer-login-avatar-5a77d3352ad604.7165486515178022931755-removebg-preview.png);\n"
"image: url(:/close_image/kisspng-scalable-vector-graphics-avatar-learning-icon-customer-login-avatar-5a77d3352ad604.7165486515178022931755-removebg-preview.png);\n"
"background-color: rgb(255, 255, 255);\n"
"border:6px solid rgb(53, 53, 53);\n"
"border-radius: 20px\n"
"}")
        self.image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.image.setObjectName("image")
        self.getUser = QtWidgets.QLineEdit(self.Login_Area)
        self.getUser.setGeometry(QtCore.QRect(90, 120, 141, 20))
        self.getUser.setStyleSheet("background-color: rgb(63, 63, 63);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;border:2px solid rgb(255, 255, 127);")
        self.getUser.setMaxLength(12)
        self.getUser.setAlignment(QtCore.Qt.AlignCenter)
        self.getUser.setObjectName("getUser")
        self.getPassword = QtWidgets.QLineEdit(self.Login_Area)
        self.getPassword.setGeometry(QtCore.QRect(90, 170, 141, 20))
        self.getPassword.setStyleSheet("background-color: rgb(63, 63, 63);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border:2px solid rgb(255, 255, 127);")
        self.getPassword.setMaxLength(12)
        self.getPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.getPassword.setAlignment(QtCore.Qt.AlignCenter)
        self.getPassword.setObjectName("getPassword")
        self.pushButton = QtWidgets.QPushButton(self.Login_Area)
        self.pushButton.setGeometry(QtCore.QRect(120, 270, 75, 23))
        self.pushButton.setStyleSheet("QPushButton:pressed{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(63, 63, 63);\n"
"border-radius:10px;\n"
"border:2px solid rgb(255, 255, 127);\n"
"color:rgb(255, 255, 255)\n"
"}\n"
"    \n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.Login_Area)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 220, 91, 23))
        self.pushButton_2.setStyleSheet("QPushButton:pressed{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(63, 63, 63);\n"
"border-radius:10px;\n"
"border:2px solid rgb(255, 255, 127);\n"
"color:rgb(255, 255, 255)\n"
"}\n"
"    ")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.Login_Area)
        self.pushButton_3.setGeometry(QtCore.QRect(45, 220, 50, 23))
        self.pushButton_3.setStyleSheet("QPushButton:pressed{\n"
                                        "    background-color: rgb(0, 0, 0);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    border-radius:10px\n"
                                        "}\n"
                                        "QPushButton{\n"
                                        "color: rgb(0, 0, 0);\n"
                                        "background-color: rgb(63, 63, 63);\n"
                                        "border-radius:10px;\n"
                                        "border:2px solid rgb(255, 255, 127);\n"
                                        "color:rgb(255, 255, 255)\n"
                                        "}\n"
                                        "    ")
        self.pushButton_3.setObjectName("pushButton_3")
        self.Rodape = QtWidgets.QFrame(self.Janela_Central)
        self.Rodape.setGeometry(QtCore.QRect(0, 419, 601, 61))
        self.Rodape.setStyleSheet("background-color: rgb(66, 66, 66);")
        self.Rodape.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Rodape.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Rodape.setObjectName("Rodape")
        self.Creditos = QtWidgets.QLabel(self.Rodape)
        self.Creditos.setGeometry(QtCore.QRect(490, 10, 91, 20))
        self.Creditos.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Creditos.setObjectName("Creditos")
        self.Error = QtWidgets.QLabel(self.centralwidget)
        self.Error.setGeometry(QtCore.QRect(-20, 10, 538, 25))
        self.Error.setStyleSheet("background-color: rgb(255, 79, 79);\n"
"border-radius: 10px")
        self.Error.setObjectName("Error")
        self.Close_error = QtWidgets.QPushButton(self.centralwidget)
        self.Close_error.setGeometry(QtCore.QRect(470, 10, 20, 16))
        self.Close_error.setMaximumSize(QtCore.QSize(20, 16777215))
        self.Close_error.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"margin-top:4px;\n"
"}")
        self.Close_error.setIconSize(QtCore.QSize(32, 32))
        self.Close_error.setCheckable(True)
        self.Close_error.setObjectName("Close_error")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.getUser.setPlaceholderText(_translate("MainWindow", "USER"))
        self.getPassword.setPlaceholderText(_translate("MainWindow", "PASSWORD"))
        self.pushButton.setText(_translate("MainWindow", "REGISTRAR"))
        self.pushButton_2.setText(_translate("MainWindow", "INSERIR IMAGEM"))
        self.pushButton_3.setText(_translate("MainWindow", "VOLTAR"))
        self.Creditos.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Criado por Kaio</p></body></html>"))
        self.Error.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">ERROR</p></body></html>"))
        self.Close_error.setText(_translate("MainWindow", "X"))
import images


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
